import '@/components/index.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next Authentication | Leonard J.',
  icons: { icon: '/favicon.svg' },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
